export const PRODUCT_DETAILS = [
  {
    "productID": "MSECOSUPER",
    "productName": "Movestone Eco Super",
    "colorOptions": "#008000,#FFD700,#0000FF,#A9A9A9",
    "motor": "1000 WT / 1200 WT",
    "controller": "55 AH",
    "tyreDiameter": "3.75-12",
    "tyreType": "CEAT & RALSON & MRF",
    "weightWithoutBattery": null,
    "breakType": null,
    "roof": "METAL",
    "shocker": "43 MM",
    "seatingCapacity": "4+1",
    "bodyDimension": null,
    "charger": "AXIOM 18 A / MICROTECH 21A",
    "battery": "EASTMAN & MUHAO",
    "rim": "ALLOY RIM / IRON",
    "mileage": "100-120",
    "sideCover": null,
    "wiper": "12V-12\"-RUBBER WIPER",
    "converter": "20Amp-48/60V",
    "headLight": "HALOGEN / LED",
    "price": null,
    "features": null,
    "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643622/Movestone/Products_new/ECO%20SS/SEN_3579_hmwqsq.jpg",
    "curtain": "UV-Resistant Polyester Canvas",
    "sideLookingGlass": "ROUND",
    "camera": "YES",
    "sensorLock": "YES",
    "rearShocker": "HYDRAULIC",
    "fireExtinguisher": "YES",
    "footMat": "YES",
    "fmSet": "YES",
    "taxiLight": "YES",
    "fan": "YES",
    "toolKit": "YES",
    "jackHandleSet": "YES",
    "passengerHandle": "YES",
    "stepnyCover": "YES",
    "fogLight": "YES",
    "category": "eRikshaw",
    "visible": "Y",
    "productPictureDetails": [
        {
            "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827721/ECOSS_green_r4z9az.webp",
            "id": 11
        },
        {
            "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827729/ECOSS_yellow_bfbqhf.webp",
            "id": 12
        },
        {
            "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827719/ECOSS_blue_jvc0ce.webp",
            "id": 13
        },
        {
            "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827718/ECOSS_grey_nsoi7p.webp",
            "id": 15
        }
    ]
},
{
  "productID": "MSDELUXE",
  "productName": "MoveStone Deluxe",
  "colorOptions": "#0000FF,#2E8B57,#C0C0C0",
  "motor": "1000 WT / 1200 WT",
  "controller": "55 AH",
  "tyreDiameter": "3.75-12",
  "tyreType": "CEAT & RALSON & MRF",
  "weightWithoutBattery": null,
  "breakType": null,
  "roof": "METAL ROOF\r\n",
  "shocker": "43 MM",
  "seatingCapacity": "4+1",
  "bodyDimension": null,
  "charger": "AXIOM 18 A / MICROTECH 21A",
  "battery": "EASTMAN & MUHAO",
  "rim": "ALLOY RIM / IRON",
  "mileage": "100-120",
  "sideCover": null,
  "wiper": "12V-12\"-RUBBER WIPER",
  "converter": "20Amp-48/60V",
  "headLight": "HALOGEN / LED",
  "price": null,
  "features": null,
  "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643916/Movestone/Products_new/Deluxe/SEN_3645_xgjjov.jpg",
  "curtain": "UV-Resistant Polyester Canvas",
  "sideLookingGlass": "ROUND",
  "camera": "YES",
  "sensorLock": "YES",
  "rearShocker": "HYDRAULIC",
  "fireExtinguisher": "YES",
  "footMat": "YES",
  "fmSet": "YES",
  "taxiLight": "YES",
  "fan": "YES",
  "toolKit": "YES",
  "jackHandleSet": "YES",
  "passengerHandle": "YES",
  "stepnyCover": "YES",
  "fogLight": "YES",
  "category": "eRikshaw",
  "visible": "Y",
  "productPictureDetails": [
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827756/DELUXE_green_qelqeu.webp",
          "id": 1
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827754/DELUXE_blue_axjncx.webp",
          "id": 2
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827752/DELUXE_deepgreen_vq3jjp.webp",
          "id": 16
      }
  ]
},
{
  "productID": "MSECOFLEXI",
  "productName": "Movestone Eco Flexi",
  "colorOptions": "#FF0000,#A9A9A9",
  "motor": "1000 WT / 1200 WT",
  "controller": "55 AH",
  "tyreDiameter": "3.75-12",
  "tyreType": "CEAT & RALSON & MRF",
  "weightWithoutBattery": null,
  "breakType": null,
  "roof": "METAL",
  "shocker": "43 MM",
  "seatingCapacity": "4+1",
  "bodyDimension": null,
  "charger": "AXIOM 18 A / MICROTECH 21A",
  "battery": "EASTMAN & MUHAO",
  "rim": "ALLOY RIM / IRON",
  "mileage": "100-120",
  "sideCover": null,
  "wiper": "12V-12\"-RUBBER WIPER",
  "converter": "20Amp-48/60V",
  "headLight": "HALOGEN / LED",
  "price": null,
  "features": null,
  "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643733/Movestone/Products_new/ECO%20FLEXI/SEN_3544_iubiuy.jpg",
  "curtain": "UV-Resistant Polyester Canvas",
  "sideLookingGlass": "ROUND",
  "camera": "NO",
  "sensorLock": "YES",
  "rearShocker": "HYDRAULIC",
  "fireExtinguisher": "YES",
  "footMat": "YES",
  "fmSet": "YES",
  "taxiLight": "YES",
  "fan": "YES",
  "toolKit": "YES",
  "jackHandleSet": "YES",
  "passengerHandle": "YES",
  "stepnyCover": "YES",
  "fogLight": "YES",
  "category": "eRikshaw",
  "visible": "Y",
  "productPictureDetails": [
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827680/ECOFLEXI_red_qrsrnu.webp",
          "id": 3
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827680/ECOFLEXI_grey_s1ezqn.webp",
          "id": 4
      }
  ]
},
{
  "productID": "MSSUPERPLUS",
  "productName": "Movestone Super Plus",
  "colorOptions": "#FF0000,#0000FF",
  "motor": "1000 WT / 1200 WT",
  "controller": "55 AH",
  "tyreDiameter": "3.75-12",
  "tyreType": "CEAT & RALSON & MRF",
  "weightWithoutBattery": null,
  "breakType": null,
  "roof": "METAL ROOF\r\n",
  "shocker": "43 MM",
  "seatingCapacity": "4+1",
  "bodyDimension": null,
  "charger": "AXIOM 18 A / MICROTECH 21A",
  "battery": "EASTMAN & MUHAO",
  "rim": "ALLOY RIM / IRON",
  "mileage": "100-120",
  "sideCover": null,
  "wiper": "12V-12\"-RUBBER WIPER",
  "converter": "20Amp-48/60V",
  "headLight": "HALOGEN / LED",
  "price": null,
  "features": null,
  "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719642741/Movestone/Products_new/SUPER%20PLUS/SEN_3590_bt9dmd.jpg",
  "curtain": "UV-Resistant Polyester Canvas",
  "sideLookingGlass": "ROUND",
  "camera": "YES",
  "sensorLock": "YES",
  "rearShocker": "HYDRAULIC",
  "fireExtinguisher": "YES",
  "footMat": "YES",
  "fmSet": "YES",
  "taxiLight": "YES",
  "fan": "YES",
  "toolKit": "YES",
  "jackHandleSet": "YES",
  "passengerHandle": "YES",
  "stepnyCover": "YES",
  "fogLight": "YES",
  "category": "eRikshaw",
  "visible": "Y",
  "productPictureDetails": [
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827597/SUPERPLUS_red_cgmzce.webp",
          "id": 5
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827597/SUPERPLUS_blue_y3uf9f.webp",
          "id": 6
      }
  ]
},{
  "productID": "MSMAXFLEXI",
  "productName": "Movestone Max Flexi",
  "colorOptions": "#C0C0C0,#2E8B57,#FF0000,#0000FF",
  "motor": "1000 WT / 1200 WT",
  "controller": "55 AH",
  "tyreDiameter": "3.75-12",
  "tyreType": "CEAT & RALSON & MRF",
  "weightWithoutBattery": null,
  "breakType": null,
  "roof": "METAL ROOF\r\n",
  "shocker": "43 MM",
  "seatingCapacity": "4+1",
  "bodyDimension": null,
  "charger": "AXIOM 18 A / MICROTECH 21A",
  "battery": "EASTMAN & MUHAO",
  "rim": "ALLOY RIM / IRON",
  "mileage": "100-120",
  "sideCover": null,
  "wiper": "12V-12\"-RUBBER WIPER",
  "converter": "20Amp-48/60V",
  "headLight": "HALOGEN / LED",
  "price": null,
  "features": null,
  "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643779/Movestone/Products_new/MAX%20FLEXI/SEN_3532_hojnb8.jpg",
  "curtain": "UV-Resistant Polyester Canvas",
  "sideLookingGlass": "ROUND",
  "camera": "NO",
  "sensorLock": "YES",
  "rearShocker": "HYDRAULIC",
  "fireExtinguisher": "YES",
  "footMat": "YES",
  "fmSet": "YES",
  "taxiLight": "YES",
  "fan": "YES",
  "toolKit": "YES",
  "jackHandleSet": "YES",
  "passengerHandle": "YES",
  "stepnyCover": "YES",
  "fogLight": "YES",
  "category": "eRikshaw",
  "visible": "Y",
  "productPictureDetails": [
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827634/MAXFLEXI_grey_z5hwuy.webp",
          "id": 7
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827636/MAXFLEXI_red_ejrfxw.webp",
          "id": 9
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827635/MAXFLEXI_blue_fncf1n.webp",
          "id": 10
      }
  ]
},
{
  "productID": "MSLOADER",
  "productName": "MoveStone Loader",
  "colorOptions": "#FF0000",
  "motor": "1000 WT / 1200 WT",
  "controller": "55 AH",
  "tyreDiameter": "3.75-12",
  "tyreType": "CEAT & RALSON & MRF",
  "weightWithoutBattery": null,
  "breakType": null,
  "roof": "METAL ROOF\r\n",
  "shocker": "43 MM",
  "seatingCapacity": "4+1",
  "bodyDimension": null,
  "charger": "AXIOM 18 A / MICROTECH 21A",
  "battery": "EASTMAN & MUHAO",
  "rim": "ALLOY RIM / IRON",
  "mileage": "100-120",
  "sideCover": null,
  "wiper": "12V-12\"-RUBBER WIPER",
  "converter": "20Amp-48/60V",
  "headLight": "HALOGEN / LED",
  "price": null,
  "features": null,
  "imageURL": "https://res.cloudinary.com/dyizlmke8/image/upload/v1719643916/Movestone/Products_new/Deluxe/SEN_3645_xgjjov.jpg",
  "curtain": "UV-Resistant Polyester Canvas",
  "sideLookingGlass": "ROUND",
  "camera": "YES",
  "sensorLock": "YES",
  "rearShocker": "HYDRAULIC",
  "fireExtinguisher": "YES",
  "footMat": "YES",
  "fmSet": "YES",
  "taxiLight": "YES",
  "fan": "YES",
  "toolKit": "YES",
  "jackHandleSet": "YES",
  "passengerHandle": "YES",
  "stepnyCover": "YES",
  "fogLight": "YES",
  "category": "loader",
  "visible": "Y",
  "productPictureDetails": [
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827797/LOADER_red1_bupbsa.webp",
          "id": 17
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827798/LOADER_red2_zfhlqp.webp",
          "id": 18
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827800/LOADER_red3_ifsqbo.webp",
          "id": 19
      },
      {
          "productImageURL": "https://res.cloudinary.com/dkoftgwba/image/upload/v1745827801/LOADER_red4_nbwyuy.webp",
          "id": 20
      }
  ]
}
]